### PR TITLE
Update API versions, single space in Authorization header, UTC time, …

### PR DESCRIPTION
**Pull request by chgeuer**
…and using the marketplace token for marketplace calls.

## Purpose

* Updated the REST `api-versions`
* `Authorization` header only single space
* The timestamp should be UTC. 
* The token used to call marketplace API was the one from a previous management call, not the subsequently fetched marketplace one.
* PowerShell files were missing end-of-file return

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by chgeuer** [comment]
Hi @dstarr , does this work for you?

**Comment by dstarr** [comment]
> Hi @dstarr , does this work for you?

This looks like a good set of enhancements to me. Sorry for the late reply, I just changed my email in GH from private email to MS so will see these in a more timelin manner.

You are free to merge or I can do it as per your preference.

**Comment by chgeuer** [comment]
I guess you will have to merge, I have no permissions here

**Comment by dstarr** [comment]
Merged

*David Starr*
ElegantCode.com // @elegantcoder <https://twitter.com/elegantcoder>
linkedin.com/in/davidstarr

**Pull request merged**
